### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by limelect** [DeveloppeurPascal/Spooch#1]
Gamolf.RTL.Scores MISSING

**Comment by DeveloppeurPascal** [comment]
Hi.

This file come from an other repository.

If you want to get all files to compile the project (at least in DEBUG mode), you should use git or a GUI to clone/download the repository with its submodules.

If you downloaded a ZIP file, you have to add the "dependencies"  manually as explained in "INSTALL" and "DEPENDENCIES" parts of the README.md file :

[DeveloppeurPascal/AboutDialog-Delphi-Component](https://github.com/DeveloppeurPascal/AboutDialog-Delphi-Component) in the sub folder ./lib-externes/AboutDialog-Delphi-Component
[DeveloppeurPascal/FMXGameEngine](https://github.com/DeveloppeurPascal/FMXGameEngine) in the sub folder ./lib-externes/FMXGameEngine
[DeveloppeurPascal/librairies](https://github.com/DeveloppeurPascal/librairies) in the sub folder ./lib-externes/librairies
